Filter nach Bundesland bei RSV liste
FixMyBerlin/rsv-dossier pull request #92
Opened 2022-10-31 13:51 UTC by rush42

Diese PR ermoeglicht das filtern nach Bundesland. Es ist bisher nur ein Entwurf und es gibt noch klaerungs Bedarf, siehe https://github.com/FixMyBerlin/private-issues/issues/37 .

2022-11-04 10:47 UTC, rush42 commented
TODO: find out why sachsen-anhalt is written lower case on the dedicated page

2022-11-07 10:12 UTC, tordans requested changes
Sieht gut aus für mich.

Aus UX-Sicht würde ich empfehlen den "Alle Bundesländer"-Link immer im Dropdown zu halten und ganz normal zu highlighten und darüber auch die Zurück-Navigation zu erlauben. Aber das ist eine inhaltiche/UX-Frage.

Habe Empfehlungen im Code kommentiert.

2022-11-07 10:12 UTC, tordans commented on src/components/Steckbrief/FederalStateOverview.tsx
> +      />
Content-Thema, aber Titel und Description sollten Unique sein. Vorschlag:

```suggestion
      <HelmetSeo
        title="Steckbriefe für BUNDESLAND"
        description="Eine Übersicht der ANZAHL Radschnellverbindungen in BUNDESLAND, Deutschland."
      />
```

2022-11-07 10:12 UTC, tordans commented on src/components/Steckbrief/FederalStateOverview.tsx
> +                <TextLink to="..">klicken Sie hier</TextLink>.
Content-Thema: "hier" ist ein großer UX-Smell.

```suggestion
                Übersicht der aktuell {radschnellwege.nodes.length} geplanten
                Radschnellverbindungen in {state}. Die Liste wird fortlaufend
                aktualisiert und ergänzt. 
                <br />
                <TextLink to=".." className="text-white hover:underline">Alle Radschnelllverbindungen im Bundesgebiet</TextLink>
```

--

Styling des Links auf dunklem Hintergrund ist off; rudimentär und ungetestet daher die Classes oben.

2022-11-07 10:12 UTC, tordans commented on src/components/Steckbrief/FederalStateOverview.tsx
> +            </h1>
SEO sollte Bundesland auflisten; außerdem Vorschlag für alternatives Wording, was das wichtige Suchwort "Radschnellverbindung" verwendet

```suggestion
            <h1 className="text-4xl font-extrabold tracking-tight text-white md:text-5xl lg:text-6xl">
              {radschnellwege.nodes.length} geplanten Radschnellverbindungen (RSV) in {state}
            </h1>
```

2022-11-07 10:12 UTC, tordans commented on src/components/Steckbrief/FederalStateList.tsx
> +                          )
UX: Ideal wäre, hier auch den selected-State hervorzuheben, bspw. mit einem leichten grauen BG.

2022-11-07 10:12 UTC, tordans commented on src/components/Steckbrief/FederalStateList.tsx
> +                            {`${state} (${stateCount[state]})`}
Das reicht so, richtig?

```suggestion
                            {state} ({stateCount[state]})
```

2022-11-07 10:12 UTC, tordans commented on src/components/Steckbrief/FederalStateList.tsx
> +                          <span className="block truncate font-normal">
HTML: Verschachtelung nicht nötig, oder?
```
<Link to={statePaths[state]} className="block truncate font-normal">
…
</Link>
```

2022-11-07 15:23 UTC, rush42 commented on src/components/Steckbrief/FederalStateOverview.tsx
> +            <div
Stimmt! Stelle mir es jedoch etwas unuebersichtlich vor, da dass div `absolut` positioniert wird, an welcher stelle wuerdest du die Component extrahieren ?

2022-11-08 07:38 UTC, tordans commented on src/components/Steckbrief/FederalStateOverview.tsx
> +            <div
Ich schau später mal in den Code. Evtl müsste/könnte man die ganze Page in einen Component packen und title, subtile und children übergeben(?)

2022-12-07 09:11 UTC, ohrie commented
@rush42 Wie ist der Stand hier? Kann das gemerged werden?

2022-12-07 19:21 UTC, tordans approved these changes
@rush42 ich hatte eine review gestartet … aber dann gesehen, dass ich eh vor Wochen schon gesagt hatte, dass ich den Code mal anschaue. Ich habe jetzt die components geshared. Schau bitte nochmal auf die dynamic route files, ob ich hier etwas übersehen habe; da war ja viel graphQL logik drin…

Ansonsten lass uns gern nochmal durchsprechen, was / warum ich geändert habe. Von meiner Seite kann es gemerged werden.

2022-12-07 19:21 UTC, tordans commented on src/components/Layout/Layout.tsx
> +  location?: WindowLocation<unknown>; // TODO: define type
Update: Umgesetzt

2022-12-08 16:45 UTC, rush42 commented
Sieht sehr gut aus! Habe noch zwei kleinigkeiten geaendert:
 - das highlithing beim filter war kaputt (nur 'Alle anzeigen' wurde bold geschrieben)
 - die default arguments von `headerTitle` und `headerDescription` sind jetzt fuer die Bundesland seiten, da diese sonst zweimal gleich definiert sind

Eine Kleinigkeit die noch fehlt:  wenn man im Filter das ausgewaehlte Bundeslandes erneut klickt, sollte sich die Liste schliessen

2022-12-08 17:26 UTC, rush42 commented
Update: I could resolve both issues above. Instead of using the `<Link>` component inside the `<Listbox.Option>` we now use the Gatsby function `navigate` inside the `onChange` callback of the `<Listbox>` component. This also enables selecting via keyboard which was not working before either.

2022-12-12 11:58 UTC, merged